### ISSUE TITLE
BE: Projects API

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-summer#15]
- get all projects for one user (public)
- create project by a user route (private, and validated route)
    - take in an array of images -> s3 (s3-multer (back-end package))
    - upload an image - multi-part form request (form data use conventions - images[])
    - take in the other basic details of project - project title, etc. 
- S3 - set AWS credentials -> do not ever post your AWS credentials on github (gitignore .env file from now on) - share credentials over slack

**Comment by evankp** [comment]
Sorry thought this was one of my issues that was in backlog for some reason lol
