### ISSUE TITLE
FE: Launch New Project Page

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-summer#17]
- combine the look and feel of Launch Page 1, with the content of Launch Page 2
- for the uploading of images - react-dropzone
     - create a general reusable component for uplaoding a series of photos

**Comment by evankp** [comment]
When you start on this, in PR #20 Login and Signup pages, I accidentally created a component for the select input as it is kind of difficult to find correct outlined styling for it with material-ui. I put it in client/src/components/inputs.js though we can discuss it when the time comes...

**Comment by DevDelvo** [comment]
Do you think I would be able to use the select input for this project page? As I was working on it, I finally understood what you meant in your warning!

**Comment by evankp** [comment]
@DevDelvo of course, I actually created it because when doing one of the login/signup pages I was looking at the wrong mockup hahaha. I'm open to helping you if you need it since I finished my tickets for last week
