### ISSUE TITLE
FS: Profile page styling/no projects or information display

### ISSUE THREAD

**Issue by evankp** [hatchways/team-summer#48]
- We should probably work on adjusting some styling of the profile page, and also show if a user has no projects, or location, etc.
- Also when there is only one project in the profile page

**Comment by evankp** [comment]
The first project has no image, and for project page, I created a "no-image" image so to speak, this might be a project card issue, but maybe you chance change the default image here?

![image](https://user-images.githubusercontent.com/22737234/70507412-28a3ab00-1ae1-11ea-8170-fa92e53f65fd.png)

![image](https://user-images.githubusercontent.com/22737234/70507429-32c5a980-1ae1-11ea-98a5-d13b54870028.png)

**Comment by evankp** [comment]
FYI Responsiveness is borked (sorry to keep adding on lol)
![image](https://i.gyazo.com/7fc35d70410c036dc77122cb22ff02bf.gif)

**Comment by tsyaeger** [comment]
Evan, not sure what you mean about the default image here. Is there a problem with the current one? (I just got it from the mui card demo, so I get that it's not ideal)
