### ISSUE TITLE
FE: Clean up on the launch project's page 

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-summer#88]
- Remove the side panel and center all the content for launching a new project
- Fix up the titles on this page

**Comment by evankp** [comment]
I am going to take over ticket as discussed with @tsyaeger on slack

**Comment by evankp** [comment]
![image](https://user-images.githubusercontent.com/22737234/70790849-bafab780-1d4a-11ea-8cbf-5274f8f13dae.png)

![image](https://user-images.githubusercontent.com/22737234/70790874-c4841f80-1d4a-11ea-8514-5a08ef68c1e1.png)
